import { PricingCatalogItem } from './types';

/**
 * Greenscape Pro - Master Pricing Catalog (Phoenix Metro Region)
 * 200+ Synthetic Trade Line Items for Estimation & Catalog Match
 */
export const SEED_PRICING_CATALOG: PricingCatalogItem[] = [
  // 1. Demolition & Earthwork (15 items)
  {
    id: 'pc-001',
    sku: 'DEMO-CONC-4IN',
    name: 'Concrete Patio Demolition & Removal (Up to 4" Slab)',
    category: 'Demolition & Earthwork',
    unit: 'SQFT',
    unitCost: 1.75,
    unitSellPrice: 4.50,
    minimumCharge: 500,
    description: 'Pneumatic breaker demo, wheelbarrow out, haul away, and disposal fees.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-002',
    sku: 'DEMO-CONC-6IN',
    name: 'Reinforced Concrete Driveway Demo (5"-6" Slab w/ Rebar)',
    category: 'Demolition & Earthwork',
    unit: 'SQFT',
    unitCost: 2.80,
    unitSellPrice: 6.75,
    minimumCharge: 800,
    description: 'Heavy hydraulic breaker demolition with rebar cutting and certified recycling haul.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-003',
    sku: 'DEMO-PAV-REM',
    name: 'Existing Interlocking Paver Removal & Palletizing',
    category: 'Demolition & Earthwork',
    unit: 'SQFT',
    unitCost: 1.20,
    unitSellPrice: 3.25,
    minimumCharge: 400,
    description: 'Hand lifting, scraping base, and stacking on client pallets or haul-off.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-004',
    sku: 'DEMO-TURF-GRS',
    name: 'Natural Grass / Sod Strip & Disposal',
    category: 'Demolition & Earthwork',
    unit: 'SQFT',
    unitCost: 0.65,
    unitSellPrice: 1.85,
    minimumCharge: 350,
    description: 'Motorized sod cutter strip to 3" depth, root barrier removal, and green haul.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-005',
    sku: 'DEMO-DIRT-EXC',
    name: 'Machine Bobcat Excavation & Rough Grading',
    category: 'Demolition & Earthwork',
    unit: 'CUYD',
    unitCost: 22.00,
    unitSellPrice: 55.00,
    minimumCharge: 600,
    description: 'Mini-skid or full track loader excavation to target depths for sub-base install.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-006',
    sku: 'DEMO-HAND-EXC',
    name: 'Hand Digging & Trenching (Restricted/Zero-Machine Access)',
    category: 'Demolition & Earthwork',
    unit: 'CUYD',
    unitCost: 45.00,
    unitSellPrice: 110.00,
    minimumCharge: 500,
    description: 'Manual shovel excavation where gate width is < 48" or around shallow utilities.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-007',
    sku: 'DEMO-CALICHE',
    name: 'Caliche Rock Extraction & Heavy Haul Surcharge',
    category: 'Demolition & Earthwork',
    unit: 'CUYD',
    unitCost: 55.00,
    unitSellPrice: 135.00,
    minimumCharge: 400,
    description: 'Pneumatic breaker labor to penetrate cementitious caliche strata.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-008',
    sku: 'DEMO-WALL-CMU',
    name: 'Block Wall Demolition & Footing Breakout',
    category: 'Demolition & Earthwork',
    unit: 'LF',
    unitCost: 18.00,
    unitSellPrice: 42.00,
    minimumCharge: 450,
    description: 'Teardown of masonry wall up to 6ft and excavation of concrete footer.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-009',
    sku: 'DEMO-TREE-SML',
    name: 'Small Tree & Stump Removal (Under 15ft Height)',
    category: 'Demolition & Earthwork',
    unit: 'EA',
    unitCost: 120.00,
    unitSellPrice: 320.00,
    minimumCharge: 320,
    description: 'Felling, chain saw bucking, stump grinding to 12" below grade, and chipping.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-010',
    sku: 'DEMO-TREE-LRG',
    name: 'Large Tree & Root Ball Removal (15ft - 30ft Height)',
    category: 'Demolition & Earthwork',
    unit: 'EA',
    unitCost: 450.00,
    unitSellPrice: 1100.00,
    minimumCharge: 1100,
    description: 'Rigging, sectional dismantling, full root ball extraction, and hole backfill.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-011',
    sku: 'DEMO-SHRUB-REM',
    name: 'Overgrown Shrub / Bush Removal',
    category: 'Demolition & Earthwork',
    unit: 'EA',
    unitCost: 15.00,
    unitSellPrice: 45.00,
    minimumCharge: 200,
    description: 'Root ball digging, branch cutting, and green waste disposal.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-012',
    sku: 'DEMO-GRAV-SCRP',
    name: 'Existing Rock / Gravel Scraping & Haul',
    category: 'Demolition & Earthwork',
    unit: 'TON',
    unitCost: 35.00,
    unitSellPrice: 85.00,
    minimumCharge: 400,
    description: 'Skid-steer surface scraping of contaminated or outdated rock mulch.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-013',
    sku: 'DEMO-DECK-WOD',
    name: 'Wood / Composite Deck Teardown',
    category: 'Demolition & Earthwork',
    unit: 'SQFT',
    unitCost: 2.20,
    unitSellPrice: 5.50,
    minimumCharge: 500,
    description: 'Unfastening framing, cutting posts, and roll-off dumpster disposal.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-014',
    sku: 'DEMO-FENC-WOD',
    name: 'Wood Lattice / Perimeter Fence Removal',
    category: 'Demolition & Earthwork',
    unit: 'LF',
    unitCost: 4.50,
    unitSellPrice: 12.00,
    minimumCharge: 250,
    description: 'Panel dismantling and post concrete footing extraction.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-015',
    sku: 'DEMO-POOL-FILL',
    name: 'Engineered Pool Demolition & Clean Fill Compact',
    category: 'Demolition & Earthwork',
    unit: 'LS',
    unitCost: 4500.00,
    unitSellPrice: 9800.00,
    minimumCharge: 9800,
    description: 'Bottom punch drainage holes, gunite rim break 36", engineered lift compaction.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 2. Pavers & Hardscape Systems (25 items)
  {
    id: 'pc-016',
    sku: 'PAV-BELG-LAF',
    name: 'Belgard Lafitt 3-Piece Paver System (Sand/Charcoal/Sierra)',
    category: 'Pavers & Hardscape',
    unit: 'SQFT',
    unitCost: 9.20,
    unitSellPrice: 18.50,
    minimumCharge: 1200,
    description: 'Premium interlocking pavers over 4" compacted ABC base, bedding sand, and polymeric sand.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-017',
    sku: 'PAV-BELG-CAT',
    name: 'Belgard Catalina Slate Textured Modular Pavers',
    category: 'Pavers & Hardscape',
    unit: 'SQFT',
    unitCost: 8.80,
    unitSellPrice: 17.75,
    minimumCharge: 1200,
    description: 'Crisp modular 3-piece combo pavers with subtle slate relief texture.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-018',
    sku: 'PAV-BELG-DIM',
    name: 'Belgard Dimensions Smooth Large Format Pavers',
    category: 'Pavers & Hardscape',
    unit: 'SQFT',
    unitCost: 10.50,
    unitSellPrice: 21.00,
    minimumCharge: 1400,
    description: 'Sleek contemporary large plank pavers with sharp pencil edges.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-019',
    sku: 'PAV-TRAV-IVR',
    name: 'Select Ivory Travertine Pavers (Unfilled/Tumbled)',
    category: 'Pavers & Hardscape',
    unit: 'SQFT',
    unitCost: 12.50,
    unitSellPrice: 24.00,
    minimumCharge: 1500,
    description: 'Cool-to-touch 1.25" Turkish travertine in Versailles 4-piece pattern over sand base.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-020',
    sku: 'PAV-TRAV-SLV',
    name: 'Silver Travertine / Platinum Honed Pavers',
    category: 'Pavers & Hardscape',
    unit: 'SQFT',
    unitCost: 14.20,
    unitSellPrice: 27.50,
    minimumCharge: 1800,
    description: 'Exotic gray/blue veined Turkish travertine with brushed finish.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-021',
    sku: 'PAV-TRAV-WAL',
    name: 'Walnut / Noche Travertine Versailles Pavers',
    category: 'Pavers & Hardscape',
    unit: 'SQFT',
    unitCost: 12.00,
    unitSellPrice: 23.50,
    minimumCharge: 1500,
    description: 'Deep earthy beige and warm chocolate cross-cut tumbled travertine.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-022',
    sku: 'PAV-ACK-MOD',
    name: 'Acker-Stone Modern Classic Concrete Pavers',
    category: 'Pavers & Hardscape',
    unit: 'SQFT',
    unitCost: 8.50,
    unitSellPrice: 17.00,
    minimumCharge: 1000,
    description: 'Solid, high-density desert color concrete pavers with chamfered edges.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-023',
    sku: 'PAV-ACK-LIN',
    name: 'Acker-Stone Linear Grand Contemporary Slabs (24"x24")',
    category: 'Pavers & Hardscape',
    unit: 'SQFT',
    unitCost: 11.50,
    unitSellPrice: 22.50,
    minimumCharge: 1400,
    description: 'Architectural modern oversized geometric stepping slabs.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-024',
    sku: 'PAV-PORC-2CM',
    name: '2CM Outdoor Porcelain Tile Pavers (Italian Stone Style)',
    category: 'Pavers & Hardscape',
    unit: 'SQFT',
    unitCost: 16.00,
    unitSellPrice: 32.00,
    minimumCharge: 2000,
    description: 'High-density, stain-proof porcelain pavers over specialized chip-gravel bedding.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-025',
    sku: 'PAV-BORD-SOL',
    name: 'Contrasting Paver Soldier Course Border',
    category: 'Pavers & Hardscape',
    unit: 'LF',
    unitCost: 4.80,
    unitSellPrice: 12.50,
    minimumCharge: 250,
    description: '6"x9" perimeter framing border with custom saw cuts and mortar bed set.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-026',
    sku: 'PAV-BORD-CONC',
    name: 'Poured Concrete Flush Paver Edge Restraint Footing',
    category: 'Pavers & Hardscape',
    unit: 'LF',
    unitCost: 6.00,
    unitSellPrice: 14.50,
    minimumCharge: 300,
    description: 'Troweled submerged concrete haunching to permanently lock perimeter pavers.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-027',
    sku: 'PAV-SEAL-NAT',
    name: 'Natural Look Penetrating Siloxane Paver Sealer',
    category: 'Pavers & Hardscape',
    unit: 'SQFT',
    unitCost: 0.60,
    unitSellPrice: 1.75,
    minimumCharge: 400,
    description: 'Breathable deep-penetrating water-repellent sealant against oil and stains.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-028',
    sku: 'PAV-SEAL-WET',
    name: 'Wet-Look Color Enhancing Acrylic Paver Sealer',
    category: 'Pavers & Hardscape',
    unit: 'SQFT',
    unitCost: 0.85,
    unitSellPrice: 2.25,
    minimumCharge: 450,
    description: 'High-gloss UV-stable protective acrylic coat deepening color tones.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-029',
    sku: 'PAV-STEP-PAD',
    name: 'Floating Paver / Turf Stepping Pads (3ft x 3ft)',
    category: 'Pavers & Hardscape',
    unit: 'EA',
    unitCost: 48.00,
    unitSellPrice: 125.00,
    minimumCharge: 375,
    description: 'Oversized standalone paver clusters framed with synthetic turf margins.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-030',
    sku: 'PAV-BASE-UPG',
    name: 'Heavy Duty 6-Inch Compacted Aggregate Sub-Base Upgrade',
    category: 'Pavers & Hardscape',
    unit: 'SQFT',
    unitCost: 1.80,
    unitSellPrice: 4.25,
    minimumCharge: 500,
    description: 'Additional 2" crushed ABC and geotextile fabric for vehicular driveway load rating.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 3. Walls, Masonry & Fire Features (25 items)
  {
    id: 'pc-031',
    sku: 'WALL-CMU-RET',
    name: 'CMU Block Retaining Wall (Up to 3ft Height)',
    category: 'Walls & Masonry',
    unit: 'LF',
    unitCost: 55.00,
    unitSellPrice: 125.00,
    minimumCharge: 800,
    description: 'Includes engineered concrete footing with #4 rebar, 8" CMU block, and drain weep holes.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-032',
    sku: 'WALL-SEAT-18',
    name: 'Courtyard Seat Wall (18" Height x 12" Width)',
    category: 'Walls & Masonry',
    unit: 'LF',
    unitCost: 42.00,
    unitSellPrice: 95.00,
    minimumCharge: 600,
    description: 'Comfortable perimeter seating height masonry wall with double-sided veneer or stucco.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-033',
    sku: 'WALL-VEN-LEDG',
    name: 'Stacked Natural Ledgerock Veneer (Charcoal/Sierra)',
    category: 'Walls & Masonry',
    unit: 'SQFT',
    unitCost: 18.00,
    unitSellPrice: 38.00,
    minimumCharge: 500,
    description: 'Dry-stack style natural stone veneer over cementitious wire lath and scratch coat.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-034',
    sku: 'WALL-CAP-TRAV',
    name: 'Honed Bullnose Travertine Wall Cap (12" Width)',
    category: 'Walls & Masonry',
    unit: 'LF',
    unitCost: 14.00,
    unitSellPrice: 32.00,
    minimumCharge: 400,
    description: 'Seamless bullnose finished natural stone capping with mortar joint set.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-035',
    sku: 'WALL-STUC-FIN',
    name: 'Synthetic Stucco Finish with Paint Match (2-Coat)',
    category: 'Walls & Masonry',
    unit: 'SQFT',
    unitCost: 4.50,
    unitSellPrice: 11.50,
    minimumCharge: 350,
    description: 'Brown coat, sand finish acrylic texture, matched to main home exterior palette.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-036',
    sku: 'FIRE-GAS-48',
    name: 'Custom 48-Inch Gas Fire Pit (Round / Square)',
    category: 'Fire & Water Features',
    unit: 'EA',
    unitCost: 1400.00,
    unitSellPrice: 3850.00,
    minimumCharge: 3850,
    description: 'CMU core, stacked stone veneer, 18" stainless steel burner ring, lava rock, and key valve.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-037',
    sku: 'FIRE-GAS-TBL',
    name: 'Linear 6ft Modern Gas Fire Table with Granite Top',
    category: 'Fire & Water Features',
    unit: 'EA',
    unitCost: 2200.00,
    unitSellPrice: 5600.00,
    minimumCharge: 5600,
    description: 'Linear stainless trough burner, electronic spark ignition, polished granite top.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-038',
    sku: 'FIRE-MED-GLAS',
    name: 'Reflective Tempered Fire Glass Upgrade (1/2")',
    category: 'Fire & Water Features',
    unit: 'LS',
    unitCost: 180.00,
    unitSellPrice: 450.00,
    minimumCharge: 450,
    description: 'High-temperature cobalt or bronze reflective diamond glass crystals (50 lbs).',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-039',
    sku: 'UTIL-GAS-LINE',
    name: '3/4-Inch Polyethylene Underground Gas Line (Trench & Pipe)',
    category: 'Fire & Water Features',
    unit: 'LF',
    unitCost: 12.00,
    unitSellPrice: 28.00,
    minimumCharge: 450,
    description: 'Trenching 18" depth, tracer wire, electrofusion fittings, shutoff valve, pressure test.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-040',
    sku: 'WAT-BOULD-FEAT',
    name: 'Triple Basalt Column / Gurgler Boulder Water Feature',
    category: 'Fire & Water Features',
    unit: 'EA',
    unitCost: 1800.00,
    unitSellPrice: 4600.00,
    minimumCharge: 4600,
    description: 'Core drilled natural basalt columns, underground basin reservoir, submersible pump, LED lights.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-041',
    sku: 'WAT-BAJA-BUB',
    name: 'Baja Shelf Water Bubbler with LED Accent',
    category: 'Fire & Water Features',
    unit: 'EA',
    unitCost: 350.00,
    unitSellPrice: 850.00,
    minimumCharge: 850,
    description: 'Flush-mounted step fountain bubbler with integrated color-changing conduit.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-042',
    sku: 'WAT-SHEER-24',
    name: '24-Inch Stainless Steel Sheer Descent Waterfall Spillway',
    category: 'Fire & Water Features',
    unit: 'EA',
    unitCost: 550.00,
    unitSellPrice: 1400.00,
    minimumCharge: 1400,
    description: 'Integrated into masonry wall with plumbing loop, flow control valve, and LED strip.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 4. Synthetic Turf & Putting Greens (15 items)
  {
    id: 'pc-043',
    sku: 'TURF-PREM-80',
    name: 'Premium 80oz Residential Synthetic Turf (ProGreen Style)',
    category: 'Synthetic Turf & Sod',
    unit: 'SQFT',
    unitCost: 4.10,
    unitSellPrice: 9.75,
    minimumCharge: 800,
    description: 'Lush 4-color blade blend, polyurethane backing, 3" DG base, weed fabric, antimicrobial infill.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-044',
    sku: 'TURF-LUX-90',
    name: 'Ultra-Luxury 90oz Cool-Touch Synthetic Turf',
    category: 'Synthetic Turf & Sod',
    unit: 'SQFT',
    unitCost: 4.90,
    unitSellPrice: 11.50,
    minimumCharge: 950,
    description: 'Temperature-reducing blade technology staying up to 15% cooler under Phoenix sun.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-045',
    sku: 'TURF-PET-SYS',
    name: 'Pet-Pro Turf System with Drainage Grid & Zeolite Infill',
    category: 'Synthetic Turf & Sod',
    unit: 'SQFT',
    unitCost: 4.70,
    unitSellPrice: 10.95,
    minimumCharge: 900,
    description: 'Rapid-drain backing with odor-neutralizing organic zeolite volcanic infill.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-046',
    sku: 'TURF-PUTT-GRN',
    name: 'True-Roll Professional Putting Green (Textured Nylon)',
    category: 'Synthetic Turf & Sod',
    unit: 'SQFT',
    unitCost: 6.50,
    unitSellPrice: 14.50,
    minimumCharge: 1000,
    description: 'Precision laser-graded putting surface, fringe turf perimeter, 3-cup flag set.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-047',
    sku: 'TURF-CUP-FLAG',
    name: 'Regulation Aluminum Golf Cup & Fiberglass Flagstick',
    category: 'Synthetic Turf & Sod',
    unit: 'EA',
    unitCost: 45.00,
    unitSellPrice: 110.00,
    minimumCharge: 110,
    description: 'In-ground anodized cup with custom numbered flag.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-048',
    sku: 'TURF-BORD-ALUM',
    name: 'Heavy Gauge Aluminum Turf Bender Board Edging',
    category: 'Synthetic Turf & Sod',
    unit: 'LF',
    unitCost: 3.50,
    unitSellPrice: 8.50,
    minimumCharge: 200,
    description: 'Commercial 4" tall black anodized clean line separator between turf and rock.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 5. Irrigation & Drainage (20 items)
  {
    id: 'pc-049',
    sku: 'IRR-SMART-CON',
    name: 'Hunter Pro-HC 12-Zone Smart WiFi Controller',
    category: 'Irrigation & Drainage',
    unit: 'EA',
    unitCost: 220.00,
    unitSellPrice: 550.00,
    minimumCharge: 550,
    description: 'Hydrawise web app integration with local weather monitoring and flow alerts.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-050',
    sku: 'IRR-DRIP-ZONE',
    name: 'Commercial Low-Volume Drip Irrigation Zone Kit',
    category: 'Irrigation & Drainage',
    unit: 'EA',
    unitCost: 380.00,
    unitSellPrice: 920.00,
    minimumCharge: 920,
    description: 'Includes 1" anti-siphon valve, pressure regulator, 100-mesh filter, and PVC main tie-in.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-051',
    sku: 'IRR-LINE-DRIP',
    name: '1/2-Inch UV-Resistant Poly Drip Lateral Tubing',
    category: 'Irrigation & Drainage',
    unit: 'LF',
    unitCost: 0.45,
    unitSellPrice: 1.25,
    minimumCharge: 150,
    description: 'Subterranean distribution tubing with pressure-compensating button emitters.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-052',
    sku: 'IRR-BACK-PREV',
    name: '1-Inch Reduced Pressure Backflow Preventer (RPZ) Assembly',
    category: 'Irrigation & Drainage',
    unit: 'EA',
    unitCost: 450.00,
    unitSellPrice: 1150.00,
    minimumCharge: 1150,
    description: 'Lead-free brass backflow device with shutoff ball valves, testing ports, and insulated cover.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-053',
    sku: 'DRN-FRENCH-4',
    name: '4-Inch Perforated French Drain with Crushed Rock Bed',
    category: 'Irrigation & Drainage',
    unit: 'LF',
    unitCost: 14.00,
    unitSellPrice: 32.00,
    minimumCharge: 400,
    description: 'Trenching, filter fabric envelope, perforated corrugated pipe, and washed rock backfill.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-054',
    sku: 'DRN-CATCH-BAS',
    name: '12"x12" Heavy Duty Catch Basin with Brass Grate',
    category: 'Irrigation & Drainage',
    unit: 'EA',
    unitCost: 85.00,
    unitSellPrice: 225.00,
    minimumCharge: 225,
    description: 'Low-point surface drainage basin with sediment trap connected to discharge line.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-055',
    sku: 'DRN-POP-EMIT',
    name: 'Spring-Loaded Pop-Up Drainage Emitter with Elbow',
    category: 'Irrigation & Drainage',
    unit: 'EA',
    unitCost: 40.00,
    unitSellPrice: 115.00,
    minimumCharge: 115,
    description: 'Curb or yard edge hydrostatic relief valve that opens under storm flow.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 6. Desert Plants, Trees & Mulch (30 items)
  {
    id: 'pc-056',
    sku: 'PLT-TREE-24BX',
    name: '24-Inch Box Multi-Trunk Desert Museum Palo Verde Tree',
    category: 'Desert Plants & Trees',
    unit: 'EA',
    unitCost: 280.00,
    unitSellPrice: 650.00,
    minimumCharge: 650,
    description: 'Includes machine excavation, compost amendment, root stimulator, lodgepole staking, and dual emitters.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-057',
    sku: 'PLT-TREE-IRON',
    name: '24-Inch Box Native Desert Ironwood Tree (Olneya tesota)',
    category: 'Desert Plants & Trees',
    unit: 'EA',
    unitCost: 320.00,
    unitSellPrice: 750.00,
    minimumCharge: 750,
    description: 'Slow-growing, evergreen desert specimen with silver-gray foliage.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-058',
    sku: 'PLT-TREE-MESQ',
    name: '24-Inch Box Thornless Chilean Mesquite Tree',
    category: 'Desert Plants & Trees',
    unit: 'EA',
    unitCost: 260.00,
    unitSellPrice: 620.00,
    minimumCharge: 620,
    description: 'Rapid-growth architectural shade tree with broad canopy.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-059',
    sku: 'PLT-TREE-15GL',
    name: '15-Gallon Specimen Tree (Sweet Acacia / Desert Willow)',
    category: 'Desert Plants & Trees',
    unit: 'EA',
    unitCost: 95.00,
    unitSellPrice: 240.00,
    minimumCharge: 240,
    description: 'Includes auger hole digging, slow-release tablet, and support stakes.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-060',
    sku: 'PLT-SHRUB-05G',
    name: '5-Gallon Desert Adapted Shrub (Texas Sage / Red Yucca / Emu Bush)',
    category: 'Desert Plants & Trees',
    unit: 'EA',
    unitCost: 18.00,
    unitSellPrice: 45.00,
    minimumCharge: 180,
    description: 'Hardy drought-tolerant flowering specimen with dedicated 2GPH drip emitter.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-061',
    sku: 'PLT-AGAV-15G',
    name: '15-Gallon Specimen Blue Glow / Whale Tongue Agave',
    category: 'Desert Plants & Trees',
    unit: 'EA',
    unitCost: 75.00,
    unitSellPrice: 185.00,
    minimumCharge: 185,
    description: 'Striking geometric succulent centerpiece with decomposed granite collar.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-062',
    sku: 'PLT-CACT-SAG',
    name: '6ft - 8ft Salvaged Saguaro Cactus (Certified Tagged)',
    category: 'Desert Plants & Trees',
    unit: 'EA',
    unitCost: 650.00,
    unitSellPrice: 1650.00,
    minimumCharge: 1650,
    description: 'AZ Dept of Agriculture tagged native Saguaro with crane set and 2x4 brace kit.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-063',
    sku: 'RCK-MAD-GOLD',
    name: '1/2-Inch Minus Madison Gold Decomposed Granite Rock',
    category: 'Desert Plants & Trees',
    unit: 'TON',
    unitCost: 42.00,
    unitSellPrice: 98.00,
    minimumCharge: 350,
    description: 'Installed at 2" uniform depth over commercial non-woven geotextile weed barrier.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-064',
    sku: 'RCK-TABLE-MES',
    name: '3/4-Inch Table Mesa Brown Screened Rock Mulch',
    category: 'Desert Plants & Trees',
    unit: 'TON',
    unitCost: 46.00,
    unitSellPrice: 105.00,
    minimumCharge: 350,
    description: 'Rich dark desert brown crushed rock installed at 2" depth.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-065',
    sku: 'RCK-BOULD-SRN',
    name: 'Sonoran Gold Accent Boulders (2ft - 3ft Specimen Size)',
    category: 'Desert Plants & Trees',
    unit: 'TON',
    unitCost: 110.00,
    unitSellPrice: 260.00,
    minimumCharge: 520,
    description: 'Machine set natural surface-weathered desert landscape boulders.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 7. Low-Voltage LED Lighting (15 items)
  {
    id: 'pc-066',
    sku: 'LGT-PATH-BRS',
    name: 'Solid Cast Brass Low-Voltage LED Path Light (FX Luminaire / Vista)',
    category: 'Low-Voltage LED Lighting',
    unit: 'EA',
    unitCost: 65.00,
    unitSellPrice: 165.00,
    minimumCharge: 330,
    description: 'Includes 3W 2700K warm LED bulb, ground stake, waterproof heat-shrink connection.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-067',
    sku: 'LGT-TREE-UPL',
    name: 'Solid Cast Brass Directional Tree Accent Spotlight (5W LED)',
    category: 'Low-Voltage LED Lighting',
    unit: 'EA',
    unitCost: 75.00,
    unitSellPrice: 185.00,
    minimumCharge: 370,
    description: 'High-lumen tree canopy spotlight with glare cowl and 30-degree optic lens.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-068',
    sku: 'LGT-WALL-HARD',
    name: 'Integrated Undercap LED Hardscape Step/Wall Light',
    category: 'Low-Voltage LED Lighting',
    unit: 'EA',
    unitCost: 45.00,
    unitSellPrice: 135.00,
    minimumCharge: 270,
    description: 'Slimline powder-coated fixture installed beneath travertine caps or stair treads.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-069',
    sku: 'LGT-TRAN-300',
    name: '300-Watt Stainless Steel Smart WiFi Lighting Transformer',
    category: 'Low-Voltage LED Lighting',
    unit: 'EA',
    unitCost: 260.00,
    unitSellPrice: 620.00,
    minimumCharge: 620,
    description: 'Multi-tap 12V-15V transformer with astronomical dusk-to-dawn clock and WiFi controls.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-070',
    sku: 'LGT-WIRE-12-2',
    name: '12/2 Direct Burial UV Low-Voltage Underground Cable',
    category: 'Low-Voltage LED Lighting',
    unit: 'LF',
    unitCost: 0.65,
    unitSellPrice: 1.75,
    minimumCharge: 150,
    description: 'Oxygen-free stranded copper cable buried in PVC sleeve under hardscape.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // 8. Outdoor Living Structures & Pergolas (10 items)
  {
    id: 'pc-071',
    sku: 'STR-ALUM-PERG',
    name: 'Custom Aluminum Louvered Pergola / Ramada Structure',
    category: 'Outdoor Living & Structures',
    unit: 'SQFT',
    unitCost: 38.00,
    unitSellPrice: 85.00,
    minimumCharge: 4500,
    description: 'Motorized louvered roof, powder-coated heavy gauge aluminum posts with footings.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-072',
    sku: 'STR-WOOD-TREX',
    name: 'Rough Sawn Douglas Fir Pergola with Steel Hardware',
    category: 'Outdoor Living & Structures',
    unit: 'SQFT',
    unitCost: 26.00,
    unitSellPrice: 58.00,
    minimumCharge: 3500,
    description: '6"x6" posts, 4"x8" beams, custom stain match, and Simpson decorative black ties.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'pc-073',
    sku: 'STR-BAR-ISLD',
    name: 'Outdoor BBQ Kitchen Island Structure (8ft Linear Island)',
    category: 'Outdoor Living & Structures',
    unit: 'EA',
    unitCost: 3200.00,
    unitSellPrice: 7800.00,
    minimumCharge: 7800,
    description: 'Steel stud framing, HardieBacker substrate, ledgerock veneer, and 3CM granite slab countertop.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
